# Generated by Django 3.1.2 on 2022-09-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_tag_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
