# Generated by Django 3.1.2 on 2022-09-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20220917_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(through='articles.Scope', to='articles.Article'),
        ),
    ]
