# Generated by Django 3.1.2 on 2022-09-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20220917_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(through='articles.Scope', to='articles.Article'),
        ),
    ]
