# Generated by Django 4.1.1 on 2022-09-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_studentteacher_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentteacher',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='school.student'),
        ),
        migrations.AlterField(
            model_name='studentteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='school.teacher'),
        ),
    ]
