# Generated by Django 4.1.1 on 2022-09-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_student_teachers_delete_studentteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='school.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='school.teacher')),
            ],
        ),
    ]
