# Generated by Django 4.1.1 on 2022-09-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_teacherstudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teachers',
        ),
    ]
