# Generated by Django 4.1.1 on 2022-09-17 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_student_teachers_alter_teacherstudents_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstudents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='school.student'),
        ),
        migrations.AlterField(
            model_name='teacherstudents',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_items', to='school.teacher'),
        ),
    ]
