# Generated by Django 4.1.1 on 2022-09-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_alter_measurement_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
